server:
  port: 80

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: none

chaos:
  security:
    social:
      qq:
        app-id:
        app-secret:
      filterProcessesUrl: /social
    browser:
      signUpUrl: /demo-signUp
#    code:
#      image:
#        length: 6
#        url: /user/*
#    browser:
#       signUpUrl: /demo-signUp
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT