language: java

sudo: false # faster builds

install: true

jdk:
  - openjdk8

notifications:
  email: false

# 国外机器可以不设置缓存
#cache:
#  directories:
#    - '$HOME/.m2'

#  常见指令
#  跳过单元测试    -DskipTests
#  跳过gpg密钥    -Dgpg.skip
#  跳过javaDoc   -Dmaven.javadoc.skip
script:
  - export TZ=Asia/Shanghai
  - mvn install -DskipTests=true -Dgpg.skip=true -B -V
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

