# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Chaos CI
on: [ push, pull_request ]

jobs:
  gradle:
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    #    strategy:
    #      matrix:
    #        #        os: [ubuntu-latest, macos-latest, windows-latest]
    #        os: [ ubuntu-latest ]
    runs-on: ubuntu-latest
    steps:
      #     初始化环境
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore gradle.properties
        run: |
          echo ${{secrets.SIGNING_SECRET_KEY_RING_FILE}} > ~/.gradle/secring.gpg.base64
          echo ${{secrets.SIGNING_CONFIG}} > ~/.gradle/config.properties
          base64 -d ~/.gradle/secring.gpg.base64 > ~/.gradle/secring.gpg
          base64 -d ~/.gradle/config.properties >> gradle.properties
          rm -rf ~/.gradle/secring.gpg.base64
          rm -rf ~/.gradle/config.properties

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Publish To MavenLocal
        run: |
          ./gradlew publishToMavenLocal

      - name: Execute Gradle build
        run: |
          ./gradlew build

      - name: Sonar Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info

      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1



