# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Gear4j CI
on: [ push ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: setupGradle
        uses: gradle/gradle-build-action@v2

      - name: buildGradle
        run: ./gradlew build

      - name: syncToGitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:gclm/gear4j.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gclm/gear4j.git

      - name: publishSnapshot
        run: |
          version="$(./gradlew properties | grep '^version:' | awk '{printf $2}')"
          echo "当前版本：$version"
          if [[ $version =~ '-SNAPSHOT' ]]; then
             ./gradlew publish
          fi
