# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Chaos CI Publish Package

on:
  push:
    tags:
      - v*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore gradle.properties
        run: |
          echo ${{secrets.SIGNING_SECRET_KEY_RING_FILE}} > ~/.gradle/secring.gpg.base64
          echo ${{secrets.SIGNING_CONFIG}} > ~/.gradle/config.properties
          base64 -d ~/.gradle/secring.gpg.base64 > ~/.gradle/secring.gpg
          base64 -d ~/.gradle/config.properties >> gradle.properties
          rm -rf ~/.gradle/secring.gpg.base64
          rm -rf ~/.gradle/config.properties

      - name: Publish To MavenLocal
        run: |
          ./gradlew publishToMavenLocal

      - name: Publish To Sonatype
        run: |
          ./gradlew publish

