name: Gear4j CI Sync
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync To Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:gclm/gear4j.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:gclm/gear4j.git

